//CENTRALIZED ACTION MODIFY HERE TO CHANGE ALL
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_ID = 'GET_ID';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';
